# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
latex: false
os:
  - osx
  - linux
r:
  - release
  - devel
  - 3.2
  - 3.3
  - 3.4
