# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: bionic
cache: packages
latex: false
warnings_are_errors: false
os:
  - linux
r:
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'


