# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

conditional_probabilities_multinomial <- function(Z, position, R, theta, N, M, n_R, C) {
    .Call('_mrf2d_conditional_probabilities_multinomial', PACKAGE = 'mrf2d', Z, position, R, theta, N, M, n_R, C)
}

gibbs_sampler_mrf <- function(init_Z, R, theta, n_steps) {
    .Call('_mrf2d_gibbs_sampler_mrf', PACKAGE = 'mrf2d', init_Z, R, theta, n_steps)
}

table_relative <- function(Z, r, C, prop) {
    .Call('_mrf2d_table_relative', PACKAGE = 'mrf2d', Z, r, C, prop)
}

table_relative_3d <- function(Z, R, C, prop) {
    .Call('_mrf2d_table_relative_3d', PACKAGE = 'mrf2d', Z, R, C, prop)
}

