# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

table_relative <- function(Z, r, C, prop) {
    .Call('_mrf2d_table_relative', PACKAGE = 'mrf2d', Z, r, C, prop)
}

table_relative_3d <- function(Z, R, C, prop) {
    .Call('_mrf2d_table_relative_3d', PACKAGE = 'mrf2d', Z, R, C, prop)
}

